### PR TITLE
IN-22 Select and Scroll Area

### PR DESCRIPTION
**Pull request by marinaDiubailo**
Task IN-22 https://yuliademidyuk.atlassian.net/browse/IN-22
Added Select component, its styles and stories.
Added Scroll area component, its styles and stories.

### CODE REVIEW

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Review by efValeron — APPROVED** [review]

**Comment by marinaDiubailo** [comment]
run build production

**Review by SukhanovPavel — APPROVED** [review]

**Pull request merged**
