### PR TITLE
Fixed Typography

### PR DESCRIPTION
**Pull request by efValeron**
Removed strict typing of the component return, for _some reason_ this was causing an error

### CODE REVIEW

**Comment by efValeron** [comment]
Removed mixin that caused problems with overriding properties

**Comment by efValeron** [comment]
npm run build

**Comment by efValeron** [comment]
run build production

**Comment by efValeron** [comment]
run build production

**Comment by efValeron** [comment]
run build production

**Review by marinaDiubailo — APPROVED** [review]

**Comment by marinaDiubailo** [comment]
Привет! Я только сейчас заметила, что у .regular-link должен быть font-size: var(--font-size-s) 14px

**Review by marinaDiubailo — APPROVED** [review]

**Review by SukhanovPavel — APPROVED** [review]

**Comment by efValeron** [comment]
run build production

**Pull request merged**
