### PR TITLE
IN-38-Layouts

### PR DESCRIPTION
**Pull request by marinaDiubailo**
**Task: https://yuliademidyuk.atlassian.net/browse/IN-38**
1. Added main Layouts: OpenLayout for auth pages, PrivateLayout for private pages (authenticated users only), HOC RootLayout for authentication status-dependent pages.
2. Wrapped the pages in a proper layout.
3. Added widgets: Header, Sidebar.
4. Added ui: Popover.

### CODE REVIEW

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Review by Halina2610 — APPROVED** [review]

**Comment by marinaDiubailo** [comment]
run build production

**Comment by Halina2610** [comment]
run build production

**Review by efValeron — APPROVED** [review]

**Pull request merged**
