### PR TITLE
IN-30 baseApi

### PR DESCRIPTION
**Pull request by marinaDiubailo**
Task: https://yuliademidyuk.atlassian.net/browse/IN-30

1. Created base RTK query api with async-mutex.
2. Added constants for domain, server api url, and some api endpoints.
3. Created local storage instance and adapter for access token storage.
4. Fix Selector component styles and add Modal to public api.

### CODE REVIEW

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
5. Added Store Provider

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Review by SukhanovPavel — APPROVED** [review]

**Comment by marinaDiubailo** [comment]
run build production

**Review by Sergey7709 — APPROVED** [review]

**Pull request merged**
