### PR TITLE
IN-25: create dropdown-menu

### PR DESCRIPTION
**Pull request by Sergey7709**
Create dropdown-menu

### CODE REVIEW

**Comment by Sergey7709** [comment]
run build production

**Comment by Sergey7709** [comment]
run build production

**Comment by Sergey7709** [comment]
run build production

**Comment by Sergey7709** [comment]
run build production

**Comment by Sergey7709** [comment]
run build production

**Comment by Sergey7709** [comment]
run build production

**Comment by Sergey7709** [comment]
run build production

**Comment by Sergey7709** [comment]
run build production

**Comment by Sergey7709** [comment]
run build production

**Comment by Sergey7709** [comment]
run build production

**Review by marinaDiubailo — APPROVED** [review]

**Review by SukhanovPavel — APPROVED** [review]

**Pull request merged**
