### PR TITLE
IN-44 create new post

### PR DESCRIPTION
**Pull request by marinaDiubailo**
Task https://yuliademidyuk.atlassian.net/browse/IN-44
1) Реализована фича создания новой публикации (поста);
2) Внесены некоторые фиксы в ui Dialog, ImageUploader, Modal;
3) Создан ui компонент Slider;

### CODE REVIEW

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Comment by marinaDiubailo** [comment]
run build production

**Review by Halina2610 — APPROVED** [review]

**Comment by marinaDiubailo** [comment]
run build production

**Review by efValeron — APPROVED** [review]

**Pull request merged**
